services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    environment:
      DATABASE_URL: "sqlite:////app/data/bioflow.db"     
      SECRET_KEY: "${SECRET_KEY}"
      ALGORITHM: "${ALGORITHM}"
      ACCESS_TOKEN_EXPIRE_MINUTES: "${ACCESS_TOKEN_EXPIRE_MINUTES}"
      ENABLE_CORS: "false"  # 前端改由 /web 同源提供，預設不開 CORS
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
      - ./data:/app/data
      - ./app:/app/app    
      - ./frontend:/app/frontend
    ports:
      - "8000:8000"

