services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    environment:
      DATABASE_URL: "sqlite:////app/data/bioflow.db"      # 明確注入，保底
      SECRET_KEY: "${SECRET_KEY}"
      ALGORITHM: "${ALGORITHM}"
      ACCESS_TOKEN_EXPIRE_MINUTES: "${ACCESS_TOKEN_EXPIRE_MINUTES}"
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
      - ./data:/app/data
    ports:
      - "8000:8000"
    # 先關掉 healthcheck，等確認起來再打開
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 5

  ui:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    env_file: .env
    environment:
      - API_BASE=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_started       # 先別用 healthy
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
      - ./data:/app/data
