services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    environment:
      DATABASE_URL: "sqlite:////app/data/bioflow.db"     
      SECRET_KEY: "${SECRET_KEY}"
      ALGORITHM: "${ALGORITHM}"
      ACCESS_TOKEN_EXPIRE_MINUTES: "${ACCESS_TOKEN_EXPIRE_MINUTES}"
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
      - ./data:/app/data
      - ./app:/app/app    
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    env_file: .env
    environment:
      - API_BASE=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_started     
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
      - ./data:/app/data
